# fix for error "Apache is running a threaded MPM, but your php7 Module is not compiled to be threadsafe."
# you need to replace mpm_event_module with mpm_prefork_module: 

sed -i "s:mpm_event_module:mpm_prefork_module:g" /etc/httpd/conf/httpd.conf
sed -i "s:mod_mpm_event.so:mod_mpm_prefork.so:g" /etc/httpd/conf/httpd.conf

# required
sed -i "s:;extension=gd:extension=gd:g" /etc/php7/php.ini
sed -i "s:;extension=pgsql:extension=pgsql:g" /etc/php7/php.ini
sed -i "s:;extension=intl:extension=intl:g" /etc/php7/php.ini
sed -i "s:;extension=mysqli:extension=mysqli:g" /etc/php7/php.ini
sed -i "s:;extension=pdo_mysql:extension=pdo_mysql:g" /etc/php7/php.ini
sed -i "s:;extension=curl:extension=curl:g" /etc/php7/php.ini
sed -i "s:;extension=iconv:extension=iconv:g" /etc/php7/php.ini


# php7 configuration
echo "LoadModule php7_module modules/libphp7.so" >> /etc/httpd/conf/httpd.conf
echo "Include conf/extra/php7_module.conf" >> /etc/httpd/conf/httpd.conf

