# fix for error "Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe."
# you need to replace mpm_event_module with mpm_prefork_module: 

sed -i "s:mpm_event_module:mpm_prefork_module:g" /etc/httpd/conf/httpd.conf
sed -i "s:mod_mpm_event.so:mod_mpm_prefork.so:g" /etc/httpd/conf/httpd.conf


# include it in /etc/httpd/conf/httpd.conf:
# php configuration
echo "LoadModule php7_module modules/libphp7.so" >> /etc/httpd/conf/httpd.conf
echo "Include conf/extra/php7_module.conf" >> /etc/httpd/conf/httpd.conf


