post_install() {
	getent group avahi &>/dev/null || groupadd -r -g 84 avahi >/dev/null
	getent passwd avahi &>/dev/null || useradd -r -u 84 -g avahi -d / -s /bin/false -c avahi avahi >/dev/null
	true
	
}

post_upgrade() {
  if (( $(vercmp $2 0.6.32rc-1) < 0 )); then
    cat <<MSG
>>> Avahi now needs to be enabled in order to launch.
    Run \`systemctl enable avahi-daemon\` if you wish
    to make use of Avahi.
MSG
  fi
}
