post_install() {
       getent group polkitd >/dev/null || groupadd -g 70 polkitd
       getent passwd polkitd >/dev/null || useradd -c 'Policy Kit Daemon' -u 70 -g polkitd -d '/' -s /bin/false polkitd
       passwd -l polkitd &>/dev/null
}

post_upgrade() {
       post_install
}

post_remove() {
       if getent passwd polkitd >/dev/null; then
               userdel polkitd
       fi
       if getent group polkitd >/dev/null; then
               groupdel polkitd
       fi
}
